name: Automatic Plugin Builder

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Files
      uses: actions/checkout@v4

    - name: Set up Java Development Kit JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    # FIXED: Added the clean command and --no-build-cache tag to force a 100% brand new download pass!
    - name: Compile and Bundle Master Jar File
      run: gradle clean jar --no-build-cache

    - name: Package Final Upload Asset
      uses: actions/upload-artifact@v4
      with:
        name: Finished-Plugin-Jar
        path: build/libs/powerboundSMP-1.0.jar
